services:
  lustrous:
    build: ./src
    ports:
      - "31337:31337"
      - "8545:8545"
    restart: unless-stopped
    environment:
      - FLAG=hitcon{redacted}
      - PORT=31337
      - HTTP_PORT=8545
      - PUBLIC_IP=localhost
      - FUNC_SIG_IS_SOLVED=is_solved()
      - SHARED_SECRET=redactedredacted
      - ENV=development
